apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: test
build:
  artifacts:
  - image: test-image
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: src
          dest: src

deploy:
  kubectl:
    manifests:
    - deploy/deployment.yml
