apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    meta.helm.sh/release-name: jenkins
    meta.helm.sh/release-namespace: jenkins
  creationTimestamp: "2021-12-21T14:38:30Z"
  generation: 6
  labels:
    app.kubernetes.io/instance: jenkins
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jenkins
    helm.sh/chart: jenkins-8.0.22
  name: jenkins
  namespace: jenkins
  resourceVersion: "49670"
  uid: 769f487f-e276-4a25-bed4-a25049960dfe
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: jenkins
      app.kubernetes.io/name: jenkins
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/secrets: b6f3d2433a174c6a66366206eeab365f7e0b15567d686362e8573c757ae6b0b9
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: jenkins
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: jenkins
        helm.sh/chart: jenkins-8.0.22
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: jenkins
                    app.kubernetes.io/name: jenkins
                namespaces:
                  - jenkins
                topologyKey: kubernetes.io/hostname
              weight: 1
      containers:
        - env:
            - name: JENKINS_USERNAME
              value: user
            - name: JENKINS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: jenkins-password
                  name: jenkins
            - name: JENKINS_HOME
              value: /bitnami/jenkins/home
            - name: DISABLE_JENKINS_INITIALIZATION
              value: "no"
            - name: JENKINS_HOST
            - name: JENKINS_EXTERNAL_HTTP_PORT_NUMBER
              value: "80"
            - name: JENKINS_EXTERNAL_HTTPS_PORT_NUMBER
              value: "443"
          image: docker.io/bitnami/jenkins:2.319.1-debian-10-r0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /login
              port: http
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: jenkins
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 8443
              name: https
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /login
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 300m
              memory: 512Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /bitnami/jenkins
              name: jenkins-data
            - mountPath: /var/run/docker.sock
              name: docker-sock
            - mountPath: /home/.m2
              name: m2
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
      terminationGracePeriodSeconds: 30
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: jenkins
        - hostPath:
            path: /var/run/docker.sock
            type: ""
          name: docker-sock
        - hostPath:
            path: /Users/kiranraj/.m2
            type: ""
          name: m2
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2021-12-26T12:25:41Z"
      lastUpdateTime: "2021-12-26T12:25:41Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2021-12-21T14:38:30Z"
      lastUpdateTime: "2021-12-26T13:02:26Z"
      message: ReplicaSet "jenkins-5594997d6b" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
  observedGeneration: 6
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1